# Required
version: 2
#
#build:
#     jobs:
#         pre_build:
#         # Generate the Sphinx configuration for this Jupyter Book so it builds.
#         - "jupyter-book config sphinx docs/"

# Define the build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.9" 
  jobs:
    post_install:
      - pip install -r docs/requirements.txt  # Documentation dependencies
      - pip install -r requirements.txt       # Project dependencies
      # - pip install git+https://github.com/Oucru-Innovations/vital-sqi.git  # Latest code from GitHub if needed
      - pip install -e .

# Sphinx configuration
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false  # Fail build on any warnings for stricter error checking

# Python setup
python:
  install:
    - requirements: docs/requirements.txt     # Documentation-specific requirements
    - requirements: requirements.txt          # Project-specific requirements
    - method: pip
      path: .

# Documentation output formats
formats:
  - pdf
  - epub
