# Required
version: 2

build:
     jobs:
         pre_build:
         # Generate the Sphinx configuration for this Jupyter Book so it builds.
         - "jupyter-book config sphinx docs/"

# Build documentation.
sphinx:
  configuration: docs/source/conf.py

# Optionally set the version of Python
python:
  version: 3.7
  install:
    - requirements: ./docs/requirements.txt
    - requirements: ./requirements.txt
    - method: pip
      path: .
