name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-travis flake8 tox pytest matplotlib==3.3.4 pytest-cov coveralls
          pip install dash-bootstrap-components dash[testing] webdriver_manager selenium
          pip install --upgrade setuptools importlib-metadata
          pip install -e .

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable libnss3
          
      - name: Install Chromedriver
        run: |
          wget http://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests with coverage
        env:
          DISPLAY: :99.0
        run: |
          Xvfb :99 & sleep 3
          pytest --cov=vital_sqi tests
            
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          coveralls-endpoint: https://coveralls.io
          path-to-lcov: ./tests  # Adjust if necessary
