name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]

    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox-travis flake8 tox pytest pytest-cov coveralls
          pip install dash-bootstrap-components dash[testing] webdriver_manager selenium
          pip install --upgrade setuptools importlib-metadata
          pip install -e .

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '131.0.6778.85'          # Use 'latest' or specify a specific version
          install-chromedriver: true        # Install the compatible ChromeDriver

      - name: Run tests with coverage
        env:
          DISPLAY: :99.0
        run: |
          Xvfb :99 & sleep 3
          pytest --cov=vital_sqi --cov-config=.coveragerc --cov-report=xml:coverage.xml --cov-report=term-missing tests
      
      - name: Debug coverage files
        run: |
          ls -la
          cat coverage.xml
      
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2.3.4
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          coveralls-endpoint: https://coveralls.io
          path-to-lcov: coverage.xml
          # path-to-lcov: ./tests 
      - name: Debug coverage paths
        run: |
          cat coverage.xml | grep filename
          echo "PWD: $(pwd)"
          find .
